In [12]:
# Q1
import numpy as np
def compute_vector_length(data):
    len_of_vector = 0
    for x in data: 
        len_of_vector += x*x
    return np.sqrt(sum(len_of_vector))

vector = np.array([ -2 , 4 , 9 , 21])
result = compute_vector_length([vector])
print(result)

23.280893453645632


In [13]:
#Q2
import numpy as np
def compute_dot_product(a,b):
    result = 0
    for i in range(0, len(a)):
        result += a[i]*b[i]
    return result
v1 = np.array ([0 , 1 , -1 , 2])
v2 = np.array ([2 , 5 , 1 , 0])
result = compute_dot_product(v1 , v2)
print(round(result ,2) )

4


In [18]:
# Q3
x = np.array([[1 , 2] , [3, 4]])
k = np.array([1 , 2])
print ("result \n", x.dot(k))

result 
 [ 5 11]


In [16]:
# Q4
x = np.array([[ -1 , 2], [3 , -4]])
k = np.array([1 , 2])
print ("result \n", x@k )

result 
 [ 3 -5]


In [21]:
# Q5

def matrix_multi_vector(a, b):
    result = np.dot(a,b)
    return result
m = np.array ([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np.array ([0 , 2 , 1])
result = matrix_multi_vector(m, v)
print (result)


[3 1]


In [23]:
# Q6
def matrix_multi_matrix(a, b):
    result = np.dot(a,b)
    return result
m1 = np. array ([[0 , 1 , 2] , [2 , -3 , 1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
result = matrix_multi_matrix(m1 , m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [24]:
#Q7
m1 = np.eye(3)
m2 = np. array([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
result = m1@m2
print ( result )

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [25]:
# Q8
m1 = np.eye (2)
m1 = np. reshape (m1 ,( -1 ,4) ) [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[5. 5. 5. 5.]


In [27]:

# Q9
m1 = np. array ([[1 , 2] , [3 , 4]])
m1 = np. reshape (m1 ,( -1 ,4) , "F") [0]
m2 = np. array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print ( result )

[29 29 29 29]


In [28]:
# Q10
def inverse_matrix(matrix):
    return np.linalg.inv(matrix)

m1 = np. array ([[ -2 , 6] , [8 , -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [31]:
# Q11
def compute_eigenvalues_eigenvectors(matrix):
    return np.linalg.eig(matrix)
matrix = np.array([[0.9, 0.2],[0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [32]:
# Q12
def compute_cosine(x, y):
    dot_product = np.dot(x, y)
    norm_x = np.linalg.norm(x)
    norm_y = np.linalg.norm(y)
    return dot_product / (norm_x * norm_y)
x = np. array ([1 , 2 , 3 , 4])
y = np. array ([1 , 0 , 3 , 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
