In [2]:
#Q1: Câu hỏi 1: Câu nào sau đây là đúng để tạo mảng 1 chiều từ 0 đến 9
import numpy as np
arr = np.arange(0, 10, 1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Q2: Cách tạo một mảng boolean 3x3 với tất cả giá trị là True
arr = np.ones((3 ,3), dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
#Q3: 
import numpy as np
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [11]:
# Q4
import numpy as np
arr = np.arange(0 ,10)
arr[arr%2 ==1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [12]:
# Q5
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape (2 , -1)
print (arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [13]:
#Q6
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat (1 ,10).reshape(2 , -1)
c = np.concatenate([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# Q7
import numpy as np
arr1 = np.arange(10).reshape(2 , -1)
arr2 = np.repeat(1 ,10).reshape(2 , -1)
c = np.concatenate([arr1, arr2], axis =1)
print ("C = ", c )

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [1]:
# Q8
import numpy as np
arr = np.array([1 ,2 ,3])
print(np.repeat( arr ,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [2]:
# Q9: 
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print("result", a[index])


result [ 6  9 10]


In [4]:
# Q10
def maxx(x,y):
    if x >= y:
        return x
    else:
        return y
a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [5]:
# Q11
a = np.array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print ("Result", np.where (a <b, b, a) )

Result [6 7 9 8 9 7 5]


In [12]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
import cv2
import matplotlib.image as mpimg


Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /Users/nguyenthingoctruc/Documents/AI/AIO2024 - Homework/AIO-Exercise/dog.jpeg
100%|███████████████████████████████████████| 33.7k/33.7k [00:00<00:00, 606kB/s]


In [14]:
img = mpimg.imread('dog.jpeg')
# gray_img_01 = 
# gray_img_01 [0 , 0]

In [16]:
R = img[:, :, 0]
G = img[:, :, 1]
B = img[:, :, 2]

In [19]:
gray_img_01 = (np.maximum(np.maximum(R, G), B) + np.minimum(np.minimum(R, G), B)) / 2
print(gray_img_01[0, 0])

102.5


In [21]:
#Q13
gray_img_02 = (R + G + B) / 3
print(gray_img_02[0, 0])


22.333333333333332


In [22]:
# Q14
gray_img_03 = 0.21 * R + 0.72 * G + 0.07 * B

print(gray_img_03[0, 0])

126.22999999999999


In [23]:
# Q15
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /Users/nguyenthingoctruc/Documents/AI/AIO2024 - Homework/AIO-Exercise/advertising.csv
100%|██████████████████████████████████████| 4.06k/4.06k [00:00<00:00, 34.2kB/s]


In [26]:
import pandas as pd
df = pd.read_csv ('advertising.csv')
data = df.to_numpy()

In [29]:

max_value = df['Sales'].max()
max_index = df['Sales'].idxmax()

print(f"Max value: {max_value}, Index: {max_index}")

Max value: 27.0, Index: 175


In [30]:
# Q16
mean_value = df['TV'].mean()

print(f"Mean value: {mean_value}")

Mean value: 147.0425


In [35]:
#Q17
Sales_higher_or_equal_20 = df[df['Sales'] >= 20].shape[0]
print(Sales_higher_or_equal_20)

40


In [38]:
#Q18 giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15:
Avg_Sales = df[df['Sales'] >= 15]['Radio'].mean()
print(Avg_Sales)

26.22293577981651


In [40]:
# Q19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn
# giá trị trung bình của cột Newspaper:
Sum_Sales = df[df['Newspaper'] >= (df['Newspaper'].mean())]['Sales'].sum()
print(Sum_Sales)

1405.1


In [45]:
# Q20:
# Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10] ChatGPT
A = df['Sales'].mean()
scores = df['Sales'].apply(lambda x: 'Good' if x > A else ('Bad' if x < A else 'Average')).to_list()
B=A
# In ra kết quả scores[7:10]
print(scores[7:10])



['Bad', 'Bad', 'Good']


In [47]:
# Q21
# Tìm giá trị gần nhất với giá trị trung bình
A = df['Sales'].iloc[(df['Sales'] - B).abs().argmin()]
# Tạo mảng mới "scores"
scores = df['Sales'].apply(lambda x: 'Good' if x > A else ('Bad' if x < A else 'Average')).to_list()

# In ra kết quả scores[7:10]
print(scores[7:10])


['Bad', 'Bad', 'Good']
