In [4]:
#Q1
import torch
import torch.nn as nn

data = torch.Tensor([1,2,3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])


In [18]:
#Q2
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(sefl,x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x)
        return exp_x/sum_exp_x

data = torch.Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
print(output)



tensor([0.7054, 0.0351, 0.2595])


In [19]:
# Q3
import torch
import torch.nn as nn

class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(sefl,x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x)
        return exp_x/sum_exp_x

data = torch.Tensor([1 , 2 , 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
print(output)



tensor([0., 0., nan])


In [20]:
# Q4:
import torch
import torch.nn as nn

class MySoftmax_Stable(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(sefl,x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x-x_max.values)
        partition =  x_exp.sum(0, keepdims = True)
        return x_exp/partition

data = torch.Tensor([1,2,3])
softmax_stable = MySoftmax_Stable()
output = softmax_stable(data)
print(output)



tensor([0.0900, 0.2447, 0.6652])


In [28]:
# Q5:
from abc import ABC , abstractmethod
class Person(ABC):
    def __init__ (self, name:str, yob:int):
        self.name = name
        self.yob = yob
    def get_yob(self):
        return self._yob
    
    @abstractmethod

    def describe(self):
        pass

class Student(Person):
    def __init__(self, name: str, yob: int, grade: int):
        super().__init__(name, yob)
        self.grade = grade

    def describe(self):
        print(self.name)
        print(self.yob)
        print(self.grade)
        return super().describe()
    
student1 = Student(name = "studentZ2023", yob =2011 , grade ="6")
student1.describe()


studentZ2023
2011
6


In [29]:
# Q6:
from abc import ABC , abstractmethod
class Person(ABC):
    def __init__ (self, name:str, yob:int):
        self.name = name
        self.yob = yob
    def get_yob(self):
        return self._yob
    
    @abstractmethod

    def describe(self):
        pass

class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: int):
        super().__init__(name, yob)
        self.subject = subject

    def describe(self):
        print(self.name)
        print(self.yob)
        print(self.subject)
        return super().describe()
    
teacher1 = Teacher(name =" teacherZ2023 ", yob =1991 , subject =" History")
teacher1.describe()


 teacherZ2023 
1991
 History


In [30]:
# Q7:
from abc import ABC , abstractmethod
class Person(ABC):
    def __init__ (self, name:str, yob:int):
        self.name = name
        self.yob = yob
    def get_yob(self):
        return self._yob
    
    @abstractmethod

    def describe(self):
        pass

class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: int):
        super().__init__(name, yob)
        self.specialist = specialist

    def describe(self):
        print(self.name)
        print(self.yob)
        print(self.specialist)
        return super().describe()
    
doctor1 = Doctor(name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists")
doctor1.describe()


 doctorZ2023 
1981
 Endocrinologists


In [37]:
# Q8:
class Ward:
    def __init__(self, name : str):
        self.__name = name
        self.__list_People = list()

    def add_person(self, person: Person):
        self.__list_People.append(person)
    
    def describe(self):
        print(f" Ward Name : { self.__name }")
        for p in self . __listPeople :
            p.describe ()

    def count_doctor(self):
        count = sum(1 for person in self.__list_People if isinstance(person, Doctor))
        return count


student1 = Student(name="studentA", yob=2010, grade="7")
teacher1 = Teacher(name="teacherA", yob=1969, subject="Math")
teacher2 = Teacher(name="teacherB", yob=1995, subject="History")
doctor1 = Doctor(name="doctorA", yob=1945, specialist="Endocrinologists")
doctor2 = Doctor(name="doctorB", yob=1975, specialist="Cardiologists")

ward1 = Ward(name="Ward1")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)

print(ward1.count_doctor())






2


In [40]:
#Q9:
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if len(self.__stack) < self.__capacity:
            self.__stack.append(value)
        return self.__stack

stack1 = MyStack(capacity =5)
stack1.push(1)
stack1.push(2)
print(stack1.is_full())

True


In [43]:
#Q10
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if len(self.__stack) < self.__capacity:
            self.__stack.append(value)
        return self.__stack
    
    def top(self):
        return self.__stack[-1]
stack1 = MyStack(capacity =5)
stack1.push(1)
stack1.push(2)
print(stack1.top())

2


In [42]:
#Q11
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def enqueue(self, value):
        return self.__queue.append(value)

queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.is_full())

False


In [45]:
#Q12
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    
    def isEmpty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    # def dequeue(self):
    
    def enqueue(self, value):
        return self.__queue.append(value)
    
    def front(self):
        return self.__queue[0]


queue1 = MyQueue(capacity =5)
queue1.enqueue(1)
queue1.enqueue(2)
print(queue1.front())

1
